name: CI/CD - Docker Build and Push to ECR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t wifi-risk-awareness .

      - name: Tag Docker image
        if: github.event_name == 'push'
        run: |
          docker tag wifi-risk-awareness:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/wifi-risk-awareness:latest

      - name: Push Docker image to ECR
        if: github.event_name == 'push'
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/wifi-risk-awareness:latest